config/routes.rb
Rails.application.routes.draw do

  get '/' => 'site#home'
  get '/popular' => 'concerts#popular'
  resources :concerts do
    resources :comments
  end

  
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :concert
  validates_presence_of :mail, :comment_field

  
    
end

app/models/concert.rb
class Concert < ActiveRecord::Base
  has_many :comments
  validates_presence_of :band, :venue, :city, :date, :description


  def self.get_concerts_day
    Concert.where("date = ?", Time.zone.now.beginning_of_day)
  end

  def self.get_concerts_month
    from = Time.now.in_time_zone.beginning_of_month
    to = Time.now.in_time_zone.end_of_month
    Concert.where(date: from..to)
  end

 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @concert = Concert.find params[:concert_id]
    @comments = @concert.comments.new
  end

  def new
    @concert = Concert.find params[:concert_id]
    @comment = @concert.comments.new
  end

  def create
    @concert = Concert.find params[:concert_id]
    @comment = @concert.comments.new comment_params
    if @comment.save
      redirect_to concert_path(@concert.id)
    else
      render 'new'
    end   
  end


  private 

  def comment_params
    params.require(:comment).permit(:mail, :comment_field)
  end 

end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController

  def index
    @concerts = Concert.all
  end

  def popular
    @concerts = Concert.all
    @sorted_concerts = @concerts.sort{|concert| concert.comments.size}    
  end

  def show
    @concert = Concert.find params[:id]
    @comment = Comment.new
  end

  def new
    @concert = Concert.new
  end

  def create
    @concert = Concert.new concert_params
    if @concert.save
      redirect_to concert_path(@concert.id)
    else
      render 'new'
    end  
  end

  private 

  def concert_params
    params.require(:concert).permit(:band, :venue, :date, :price, :city, :description)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  
  def home
    @today_concerts = Concert.get_concerts_day
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/concerts/index.html.erb
<% @concerts.each do |concert| %>
      
      <div class="panel panel-default">
        <div class="panel-body">
       <%= link_to(concert.band, concert_path(concert.id)) %> - <%= concert.city %> - <%= concert.description %>
        </div>
      </div>   

  <% end %>

app/views/concerts/new.html.erb
<h3>Add a new wonderful concert</h3>

 <%= form_for [@concert] do |f| %>

  <br>
  <%= f.label :band %>
  <%= f.text_field :band %>
  <br>
  <%= f.label :date %>
  <%= f.date_field :date %>
  <br>
  <%= f.label :venue %>
  <%= f.text_field :venue %>
  <br>
  <%= f.label :city %>
  <%= f.text_field :city %>
  <br>
  <%= f.label :price %>
  <%= f.number_field :price %>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description %>


  <%= f.submit 'Save' %>
  <%= link_to('Cancel', '/') %>

<% end %>

app/views/concerts/popular.html.erb
<% @sorted_concerts.each do |concert| %>
      
  <div class="panel panel-default">
    <div class="panel-body">
   <%= link_to(concert.band, concert_path(concert.id)) %> - <%= concert.city %> - <%= concert.description %>
    </div>
  </div>   

  <% end %>

app/views/concerts/show.html.erb
<div class="panel panel-danger">
  <div class="panel-heading">
    <h3><%= "#{@concert.band}" %></h3>
  </div>
  <div class="panel-body">
    <p><strong>Date:</strong><%= " #{@concert.date}" %></o>
    <p><strong>Where: </strong><%= "#{@concert.venue}, #{@concert.city}"%></p>
    <p><strong>How much:</strong><%= " #{@concert.price} €"%></p>
    <p><strong>Tell me more:</strong><%= " #{@concert.description}" %></p>
  </div>
</div>

<div class="panel panel-default">
  <% @concert.comments.each do |comment| %>

    <div class="panel-heading"> <strong><%= comment.mail %></strong> has said at <%= comment.created_at %></div>
    <div class="panel-body">
      <%= comment.comment_field %>
    </div>
  <% end %>
</div>

<%= form_for [@concert, @comment] do |f| %>

  <%= f.label "email" %> <br>
  <%= f.email_field :mail %>
  <br>
  <%= f.label "Comment" %> <br>
  <%= f.text_area :comment_field %>
  <br>

  <%= f.submit 'Send comment' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicConcertNetwork</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
  <ul class="list-inline">
    <li><%= link_to('Home', '/') %></li>
    <li><%= link_to('+ Add a new concert', new_concert_path) %></li>
    <li><%= link_to('+ Popular concerts', popular_path) %></li>
    <li class="divider"></li>
    <li><%= link_to('See all concerts', concerts_path) %></li>
  </ul>   
  </div>
</nav>
</header>

  <div class="container">
    <div class="row">

      <div class="col-md-8">
        <%= yield %>
      </div>
      <div class="col-md-4">

        <div class="list-group">

        <h4> Later this month </h4>
        <% Concert.get_concerts_month.each do |concert| %>

            <span class="list-group-item">
              <h4 class="list-group-item-heading"><strong><%= link_to(concert.band, concert_path(concert.id)) %></strong></h4>
                <p class="list-group-item-text"><strong>Date:</strong><%= " #{concert.date}" %></p></p>
                <p class="list-group-item-text"><p><strong>Where: </strong><%= "#{concert.venue}, #{concert.city}"%></p>
                <p class="list-group-item-text"><p><strong>How much:</strong><%= " #{concert.price} €"%></p>
                <p class="list-group-item-text"><p><strong>Tell me more:</strong><%= " #{concert.description}" %></p>
              </span>  
        <% end %>      
        </div> 

    </div>
  </div>

  <footer class="footer">
    <nav class="navbar navbar-default navbar-fixed-bottom ">
      <div class="container">
     
      <p> I'm a footer </p>

      </div>
    </nav>
  </footer>
</body>

</html>

app/views/site/home.html.erb
<h2><strong>Hey!</strong> <br> What's happening today?</h2>


<div class="panel panel-danger">
<% @today_concerts.each do |concert| %>
  <div class="panel-heading">
    <h3><%= link_to(concert.band, concert_path(concert.id))%></h3>
  </div>
  <div class="panel-body">
    <p><strong>Date:</strong><%= " #{concert.date}" %></p>
    <p><strong>Where: </strong><%= "#{concert.venue}, #{concert.city}"%></p>
    <p><strong>How much:</strong><%= " #{concert.price} €"%></p>
    <p><strong>Tell me more:</strong><%= " #{concert.description}" %></p>
  </div>
  <% end %>
</div>